### ISSUE TITLE
Instant validation/feedback

### ISSUE THREAD

**Issue by sumanthratna** [hotwire-django/django-turbo-allauth#1]
# Feature Request
it would be very useful if forms could display instant feedback. One problem I often encounter with instant validation in Django is that POSTing to a form route results in the data being saved to the DB if the data is valid, which should not happen (data should only be saved in the DB when the user clicks submit). 

# Potential Implementation
create a mixin that overrides `save` such that `commit=False` is passed when an HTTP parameter called `validateOnly` is passed

**Comment by danjac** [comment]
This is out of scope for this library, which is an adapter for allauth views while maintaining the same functionality while using Turbo validation workflow.
